create table sample_superstore (
    Row_ID int primary key,
    Order_Priority nvarchar(20),
    Discount decimal(4,2),
    Unit_Price float,
    Shipping_Cost float,
    Customer_ID int,
    Customer_Name nvarchar(100),
    Ship_Mode nvarchar(20),
    Customer_Segment nvarchar(50),
    Product_Category nvarchar(50),
    Product_Sub_Category nvarchar(50),
    Product_Container nvarchar(50),
    Product_Name nvarchar(200),
    Product_Base_Margin float,
    Region nvarchar(20),
    State_or_Province nvarchar(50),
    City nvarchar(50),
    Postal_Code int,
    Order_Date date,
    Ship_Date date,
    Profit float,
    Quantity_ordered_new tinyint,
    Sales float,
    Order_ID int,
    Month nvarchar(20),
    year smallint
);